### ISSUE TITLE
Total Datasets -1

### ISSUE THREAD

**Issue by JGulic** [NextGeoss/ckanext-kpis#3]
The number of Total Datasets in the kpis page in Total Datasets tab displays wrong number of datasets that are available in the portal

**Comment by kmbn** [comment]
Pull request #5 fixes the cause of this issue (negative dataset count).

There's a related issue regarding the potential for dataset counts that are (or seem to be) too high: #4. It has different causes than the negative count and might require a decision about what datasets we want to count.
